export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
  COMPANY = 'COMPANY'
}

export enum ApplicationStatus {
  APPLIED = 'APPLIED',
  SHORTLISTED = 'SHORTLISTED',
  HIRED = 'HIRED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN'
}

export enum GigOrderStatus {
  PENDING = 'PENDING',
  QUOTE_SENT = 'QUOTE_SENT',
  QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  DELIVERED = 'DELIVERED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  DISPUTED = 'DISPUTED',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED'
}

export enum ChatType {
  JOB = 'JOB',
  GIG = 'GIG',
  DIRECT = 'DIRECT'
}

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  GIG_PAYMENT = 'GIG_PAYMENT',
  GIG_REFUND = 'GIG_REFUND',
  GIG_REVENUE = 'GIG_REVENUE'
}

export enum DisputeResolution {
  PENDING = 'PENDING',
  REFUND_BUYER = 'REFUND_BUYER',
  RELEASE_PAYMENT = 'RELEASE_PAYMENT'
}

export enum NotificationType {
  NEW_MESSAGE = 'NEW_MESSAGE',
  JOB_SHORTLISTED = 'JOB_SHORTLISTED',
  GIG_DELIVERED = 'GIG_DELIVERED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  DISPUTE_UPDATE = 'DISPUTE_UPDATE'
}
